ansible_become_pass: ENC[AES256_GCM,data:KVE2MvurPhA=,iv:SbDV11McNQC8PBlO6LuDMGB/5EZRHLQi+tlwoUYy+zg=,tag:vGEIvNUcx8h1gpoa3AEgLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zhrmunqh9krvus7f82gvkpjjfepksy729c7nq66jf4uhzs53334sv7rqk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhYnhQZHJGalRjaVpHKzA3
            M3dIUlhTbDZTamRaNFloZE8yY2RYOWdRQ3hNClVMVmFEdUtldVJpYjNUU3ZnVW5z
            NlBES1BrTnJaZWdMRWJjY0xTRlhkdjgKLS0tIFhFZ2V1YVpNejVrTUwzbXpnRXEv
            dEY3NmZQU21aNkd2SktHbzJ1NFJiY1UKSE0ZTVPsvrmYwRmLF+K2p9Z5fbQihTgI
            NpKAMd2x8o8X3UcopiLl3udXt5RVycL7DfFgr7ADdrRjmWm4eMvokw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T09:16:22Z"
    mac: ENC[AES256_GCM,data:wiZnNn3EjXyWkMu78IL1ls1tp69jX30+OEa2X0t50mPcpDUxjct7MGKAVwJFAjD3c5tgdCKb2WaZv6O6rovM8oCo6ceTOF+pFZSOdcX2gxu5Lr/aVSnj100wWXL2U+E3Dr43qHB04FeZaVYHmb9Iw0Auk0OnrvySHAmYfhtu40k=,iv:mSsme01uF2k7m2aiPKsh60tWax5F8scbXEJwvSmkAt0=,tag:QaOGum1bbbg2lkZlNnqZfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
