apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7xutsderSRuU4fCkJV3B97Kg3JS9uGlb,iv:MwX3Sl0b5VkB42qm8pg369w6O1ljEd/4WIn4Ziv8c+g=,tag:h3ZNGG+fZ4jw3JzxR87fKg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zhrmunqh9krvus7f82gvkpjjfepksy729c7nq66jf4uhzs53334sv7rqk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWWs2S1JKbkxjK1NpVGln
            RVJZbit5RUFRZlEwTEtFN0lxVlRGSjRpMjE0Ckp6RGFzbW5VdUlnUU1aUk01OTFH
            VW1JOVNDSzFYTG8wYmNnYzFIZEZxUzQKLS0tIDN0dmNmOSszdVlHVFhuQjBrZ2Iz
            c3dPWmNOYmI2dDFYUnVVdFFmOTY3MTAKuQnjYfrLIOTXUWoK4Cnz0cQalqW50cxS
            jGEWrxEFlsbvDnQddlBrzpiP51R3nszZ4ZJL3/ndncEwfDE9m/MsjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T09:17:26Z"
    mac: ENC[AES256_GCM,data:8IYfotfUymO+Nmi05jf+q0BPSMJswU3izxE3odoHHcUSwxL3iggwHergLumlFkF2NoJgkyXjU3rY1uPJ7EeHUbsnmrLBtCM8xSb5r2HU9/rn05WLf7/np+EJoS1O0s6fZ/q4m8HiQAPrTcgRu3yfkfHvqEeubzJMQ1Pa6yienus=,iv:ijH/SwrKbkVmuqKPzkmrrCWtM3Nb8/4plnPO0+AKQU4=,tag:wqpfpGjhvAyN+qg1lyiFuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
