apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eB3VGAHvsEdgPt50TY2gB2Wi35JQ10rE,iv:DF+gZ7ZQfQ8YWIGq9sm5DBMfyYSRgLgFn8drwPTT5BE=,tag:zZnKKFbkHA6I+T+xUHHTEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zhrmunqh9krvus7f82gvkpjjfepksy729c7nq66jf4uhzs53334sv7rqk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WkNZdzNnUEU2NXJEWEtT
            WGloMWdLYnNZWFpVSUg4a0VhenNsWGx2S0NrCmx6TUsrUEl5dlB4bmJkdnpUWGd3
            VHlZanB6cmZrVys1L2FOSmQzZFBUOUUKLS0tIHM1OW9neWJaN1YrTzMrVDlDQkhz
            Z01OM201Z3lXS21HekQvTE9QUC9WRWMKvtovfiD1R2K2KExdIy/9UE4tlQz7A3Tj
            Y1Kaw5HhzlZA8d6foDWS0QEeH9J48O/EWiztXhR6HBFWzKzP2uITTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T08:03:11Z"
    mac: ENC[AES256_GCM,data:ySYoNme74Fcl5EP+xlkMjHhy/zZuBoVvLBbfd27bJbRCZyRP+FRiSuWcSf1PCG1Fi3EkHIOhZRlzsGwlH7FVKBMgaBHwpu/Rq69vUwoKlDpWonr+fM3MgWazG3BVfHoZobHQMqFB2MPLcnbbWz/0i1euIaeS/T+7sj/wGV0iwsw=,iv:OqI7gAcHmWkMmrAuUHR2UjdXrhpOX71YLyiY+N41bK4=,tag:x9ZW1VIGVUFzAo7GZOivYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
