apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:1W63C+h1l/Gl70CyGoofIVwUKQ6SqMf+txM7QKRsrgGO0kSH,iv:WzwpIZ+gDWz27HRgyrEkIcHVpcQFBH4PWAUpXqW+Odo=,tag:hVxiiNJ7Wn9oHOdeicSGdg==,type:str]
    credentials.json: ENC[AES256_GCM,data:OQ9VphuV3petsVD+XDKe3Dx16sAbYmu/oVQOhI3D+ul4ZCV7GxDMqloGO+bPus9p60dawk1aFSC30bN8kL3dcew1DPrPj1eCnQXazrjc0/SsKsgD87afN5zrYJ3dcLNP9iKTnNbM1OSNc16zcCdkCpjw4LukxTHLfPG3gzYHCi1H8SPgAdiSq8/UJzpGmxaFUA6YGIyGzUbopmGEifHkftmvKqCYv6uL+p/KOr3a9g==,iv:xNroZfw9a6AAFr8HM6gZb16PZwos1E8wHhE1O3CcgC4=,tag:ki3wZ4JpAg54rXXdkh045w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zhrmunqh9krvus7f82gvkpjjfepksy729c7nq66jf4uhzs53334sv7rqk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmQWlWZWdaZW5PS2dIbWJw
            VWhES20xQzBZd1lWbGNXTURybTlzVHBJZ1hRCktnVWRLTTlUaEFMamtYVFRFaFNE
            Tll1NTk1d092YllrcEt6eFNNMmxGd2cKLS0tIE11QU1WM1h1czFOd09lbEhOSGIx
            N0VaaXJ0N1d3NmNZbTZLZWI2dDRwNUkKmcWhdn0eNa/LQ8g9PlNmwPxbYG0MJaP+
            yiSUQM4NsYeOP3eCSMRvgef2e4a4RQSE8kHmP47KNv08lr96974nTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-22T08:22:33Z"
    mac: ENC[AES256_GCM,data:BlVSLswLuziaoDy3ouHCfCVs4NQlcMIy/EQVU6VKiShqe9S58x1tuXs9orxUX7jG9M2DKQ7fRxDGmZp9da23y3nDvARzL1Q45z65SMTeHCK3qw9AZzHN5XcVRYZn9bf3yFd6xmb0fymK6JR8ZKhpAtDcAy4b7eZ6TpIgDhfnV2k=,iv:n1umF2/SVWpLHl2SjQHBG8kXIyFfIaU6vbaJqIO/e1Y=,tag:ZYK07XVgFvJyUyUUtf8+0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
